'use strict';

// =============================================================================
// YNDA GOOGLE SHEETS DATA ARCHITECTURE (XXXV)
// Mọi tab/header đội nghiệp vụ được định nghĩa tập trung tại đây.
// Các bảng bắt buộc (không được bỏ): USERS, TASKS, TASK_CLAIMS,
// TASK_ASSIGNMENTS, TASK_SUBMISSIONS, TASK_REVIEWS, ROLE_REVIEWS,
// XP_TRANSACTIONS, BONUS_TRANSACTIONS, SEASONS, LEADERBOARDS,
// NOTIFICATIONS, PRODUCTION_TEAMS, AUDIT_LOGS.
// Có thể bổ sung tab kỹ thuật nhưng không được làm mất các bảng trên.
// =============================================================================

// Lưu ý: header dùng tiếng Việt không dấu để ổn định với Google Sheets.
// Các trường datetime lưu ISO-8601 (Asia/Ho_Chi_Minh).
const SCHEMA = {
  USERS: [
    'USER_ID', 'NAME', 'EMAIL', 'ROLE', 'DEPARTMENT', 'SEASON_ID',
    'STATUS', 'PHONE', 'AVATAR', 'PASSWORD_HASH', 'FIREBASE_UID',
    'JOINED_AT', 'CREATED_BY', 'CREATED_AT', 'UPDATED_AT'
  ],
  TASKS: [
    'TASK_ID', 'CODE', 'TITLE', 'DESCRIPTION', 'EXPECTED_OUTPUT',
    'SKILLS', 'STEPS', 'SCOPE', 'TASK_TYPE', 'DEPARTMENT',
    'TEMPLATE_ID', 'XP_AI_RECOMMENDED', 'XP_FINAL', 'XP_OVERRIDE_REASON',
    'DIFFICULTY', 'DIFFICULTY_REASON', 'ESTIMATED_TIME_MIN', 'PROOF_REQUIREMENT',
    'PROOF_FORMAT', 'AI_VERIFY', 'REVIEWER_ROLE', 'REVIEWER_DEPARTMENT',
    'SLOTS', 'UNLIMITED_SLOTS', 'OPEN_TIME', 'CLAIM_DEADLINE', 'WORK_START',
    'SUBMISSION_DEADLINE', 'STATUS', 'IS_TEAM_TASK', 'TOTAL_XP', 'BREAKDOWN',
    'MANDATORY_ELIGIBLE', 'FORCED', 'CREATED_BY', 'CREATED_AT', 'UPDATED_AT',
    'DRIVE_FOLDER_ID', 'SEASON_ID', 'ARCHIVED_AT'
  ],
  TASK_CLAIMS: [
    'CLAIM_ID', 'TASK_ID', 'USER_ID', 'STATUS', 'CLAIMED_AT', 'STARTED_AT',
    'SUBMITTED_AT', 'SLOT', 'XP_POLICY', 'CREATED_AT', 'UPDATED_AT'
  ],
  TASK_ASSIGNMENTS: [
    'ASSIGNMENT_ID', 'TASK_ID', 'ASSIGNER', 'ASSIGNEE', 'ASSIGNED_AT',
    'DUE_TIME', 'ASSIGNMENT_TYPE', 'REASON', 'STATUS', 'NOTE',
    'XP_POLICY', 'ACCEPTED_AT', 'STARTED_AT', 'SUBMITTED_AT',
    'CREATED_AT', 'UPDATED_AT'
  ],
  TASK_SUBMISSIONS: [
    'SUBMISSION_ID', 'TASK_ID', 'CLAIM_ID', 'ASSIGNMENT_ID', 'USER_ID',
    'VERSION', 'PROOF', 'PROOF_FILES', 'DRIVE_PATH', 'STATUS',
    'AI_VERDICT', 'AI_REPORT', 'SUBMITTED_AT', 'REVIEWED_AT',
    'REVIEWER', 'HUMAN_VERDICT', 'HUMAN_REASON', 'BASE_XP',
    'QUALITY_BONUS_XP', 'PENALTY_XP', 'FINAL_XP', 'CREATED_AT'
  ],
  TASK_REVIEWS: [
    'REVIEW_ID', 'TASK_ID', 'SUBMISSION_ID', 'REVIEWER', 'REVIEW_TYPE',
    'VERDICT', 'REASON', 'REPORT', 'CREATED_AT'
  ],
  ROLE_REVIEWS: [
    'REVIEW_ID', 'SEASON_ID', 'WEEK', 'TEAM', 'MEMBER_ID', 'MEMBER_NAME',
    'ROLE', 'DEFAULT_ROLE_POINT', 'AI_RECOMMENDED', 'AI_REASON',
    'FINAL_ROLE_POINT', 'REVIEWER', 'STATUS', 'NOTE', 'CREATED_AT', 'UPDATED_AT'
  ],
  XP_TRANSACTIONS: [
    'TRANSACTION_ID', 'USER_ID', 'TIME', 'TYPE', 'SOURCE_ID', 'SOURCE_NAME',
    'RAW_POINT', 'APPLIED_POINT', 'STATUS', 'REVIEWER', 'NOTES',
    'CREATED_BY', 'IS_ROLE_POINT', 'ROLE_CONVERSION', 'ROLE_RAW_POINT',
    'ROLE_OVERALL_VALUE', 'COUNT_IN_OVERALL', 'SEASON_ID', 'CREATED_AT'
  ],
  BONUS_TRANSACTIONS: [
    'BONUS_ID', 'USER_ID', 'TYPE', 'XP', 'PROOF', 'REASON', 'REVIEWER',
    'STATUS', 'CREATED_BY', 'CREATED_AT', 'SEASON_ID', 'GROUP_COUNT', 'GROUP_LINK'
  ],
  SEASONS: [
    'SEASON_ID', 'NAME', 'START_DATE', 'END_DATE', 'STATUS', 'LOCKED_AT',
    'CREATED_BY', 'CREATED_AT'
  ],
  LEADERBOARDS: [
    'LEADERBOARD_ID', 'SEASON_ID', 'SNAPSHOT_TYPE', 'PERIOD', 'USER_ID',
    'OVERALL_XP', 'TASK_XP', 'BONUS_XP', 'PENALTY_XP', 'ROLE_POINT',
    'ROLE_CONTRIBUTION', 'COMPLETED_COUNT', 'RANK', 'CREATED_AT'
  ],
  NOTIFICATIONS: [
    'NOTIFICATION_ID', 'USER_ID', 'CHANNEL', 'TYPE', 'TITLE', 'BODY',
    'LINK', 'STATUS', 'CREATED_AT', 'READ_AT'
  ],
  PRODUCTION_TEAMS: [
    'TEAM_ID', 'NAME', 'PROJECT_LINK', 'STATUS', 'MEMBERS', 'TASK_IDS',
    'SEASON_ID', 'CREATED_BY', 'CREATED_AT'
  ],
  AUDIT_LOGS: [
    'LOG_ID', 'TIME', 'ACTOR', 'ACTOR_ROLE', 'ACTION', 'ENTITY_TYPE',
    'ENTITY_ID', 'BEFORE', 'AFTER', 'REASON', 'CREATED_AT'
  ],
  TASK_TEMPLATES: [
    'TEMPLATE_ID', 'CODE', 'NAME', 'DESCRIPTION', 'SCOPE', 'DEPARTMENT',
    'XP_SUGGESTION', 'PROOF_FORMAT', 'DEFAULT_OPEN', 'DEFAULT_CLAIM',
    'DEFAULT_WORK', 'DEFAULT_SUBMIT', 'AI_VERIFY', 'REVIEWER_ROLE',
    'REVIEWER_DEPARTMENT', 'FIELDS'
  ],
  INTERACTIONS: [
    'INTERACTION_ID', 'TASK_ID', 'USER_ID', 'PLATFORM', 'ACTION', 'WINDOW',
    'SUMMARY_ID', 'POST_ID', 'DEDUPE_KEY', 'CREATED_AT'
  ],
  SEASON_SCORES: [
    'SCORE_ID', 'SEASON_ID', 'USER_ID', 'SCORE_TYPE', 'SCORE_VALUE', 'CREATED_AT'
  ]
};

// Các bảng không thể để InMemory lưu cục bộ: task code counter
const COUNTERS = ['TASK_CODE_COUNTER'];

module.exports = { SCHEMA, COUNTERS };